accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='Register'),
    path('login/', views.UserLoginView.as_view(), name='Login'),
    path('logout/', views.UserLogoutView.as_view(), name='Logout')
]

task_app/urls.py
from django.contrib import admin
from django.urls import path
from task_app import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='Home'),
    path('create/', views.TaskCreateView.as_view(), name='Create'),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name='Update'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='Delete'),
    
]

task_project/urls.py
from django.contrib import admin
from django.urls import path, include
from task_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_app.urls')),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

task_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    STATUSES = {
        'on_progress': 'On Progress',
        'completed': 'Completed',
        'not_started': 'Not started'
    }

    PRIORITIES = {
        'low': 'Low priority',
        'high': 'High priority',
        'medium': 'Medium priority'
    }

    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    status = models.CharField(max_length=255, choices=STATUSES, default='not_started')
    priority = models.CharField(max_length=255, choices=PRIORITIES, default='low')

    deadline = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    image = models.ImageField()
    file = models.FileField(blank=True, null=True, upload_to='task_files/')

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    content = models.TextField()
    file = models.FileField(blank=True, null=True, upload_to='task_files/')
    
    def __str__(self):
        return f'Comment by {self.user} to {self.task}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })
            

task_app/forms.py
from django import forms
from .models import Task # Припустимо, у вас є модель Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'priority', 'status', 'file', 'image'] # Поля для форми


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2', })

        self.fields['deadline'].widget = forms.DateInput(attrs={'type': 'datetime-local', 'class': 'form-control mb-2'})


class FilterForm(forms.Form):
    STATUSES = {
        '': 'All',
        'on_progress': 'On Progress',
        'completed': 'Completed',
        'not_started': 'Not started'
    }

    PRIORITIES = {
        '': 'All',
        'low': 'Low priority',
        'high': 'High priority',
        'medium': 'Medium priority'
    }

    priority = forms.ChoiceField(choices=PRIORITIES, label='Priorities', required=False)
    status = forms.ChoiceField(choices=STATUSES, label='Statuses', required=False)

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.models import User
from accounts.forms import RegisterForm, LoginForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('Home')


    

class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'login.html'

class UserLogoutView(LogoutView):
    model = User
    next_page = 'Home'
    

task_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Task, Comment
from .forms import TaskForm, FilterForm

class TaskListView(ListView):
    model = Task
    template_name = 'task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        
        tasks =  Task.objects.filter(user=self.request.user).all()
        status = self.request.GET.get('status', '')
        priority = self.request.GET.get('priority', '')

        if status:
            tasks = tasks.filter(status=status)

        if priority:
            tasks = tasks.filter(priority=priority)

        return tasks
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterForm'] = FilterForm(self.request.GET)
        return context
# Create your views here.

class TaskCreateView(CreateView):
    model = Task
    template_name = 'task_created.html'
    success_url = reverse_lazy('Home')

    ordering = ['-created-at']


    form_class = TaskForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'task_update.html'
    success_url = reverse_lazy('Home')  

    form_class = TaskForm

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'task_delete.html'
    success_url = reverse_lazy('Home')

    

templates/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Сайт {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    {% load static %}
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container mt-4">
    {% block content %}

    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Логін</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button type="submit" class="btn btn-primary">Увійти</button>
    </form>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Реєстрація</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_div}}
        <button type="submit" class="btn btn-primary">Зареєструватися</button>
    </form>
{% endblock %}

templates/task_created.html
{% extends 'base.html' %}

{% block content %}
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {{form.as_div}}
        
        <button type="submit">Sumbit</button>
    </form>
{% endblock content %} 

templates/task_delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Ви впевнені, що хочете видалити задачу</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Так</button>
        <a class="btn btn-dark" href="{% url 'Update' task.id %}">Ні</a>
        
    </form>
{% endblock content %}

templates/task_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        
        <h1>Список задач</h1>
        <form action="" method="get">
            {{filterForm.as_p}}
            <button type="submit"><i class="bi bi-funnel"></i></button>
        </form>
        {% if user.is_authenticated %}
            <form action="{% url 'Logout' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-outline-danger position-absolute top-0 end-0 mt-2 me-2" type="submit">Logout</button>
            </form>

        {% else %}
            <a href="{% url 'Login' %}" class="btn btn-primary position-absolute top-0 end-0 mt-2 me-2">Login</a>
        {% endif %}
        <div class="list-group">
            {% for task in tasks %}
            
                <a href="{% url 'Update' task.id %}" class="gap-2 align-items-center d-flex list-group-item list-group-item-action">
                    <b>{{task.title}}</b>
                    <span class="badge rounded-pill text-bg-info">{{task.get_status_display}}</span>
                    <span class="badge rounded-pill text-bg-success">{{task.get_priority_display}}</span>

                    <span class="ms-auto">{{task.deadline}}</span>
                </a>
            {% endfor %}
        </div>


        <a href='{% url "Create" %}' class="btn btn-primary mt-3">Добавити задачу</a>
    </div>
{% endblock content %}

templates/task_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Редагувати задачу</h1>
        <form class="mb-5" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-bookmark-fill"></i> Зберегти</button>
            <a class="btn btn-danger" href="{% url 'Delete' task.id %}">
                <i class="bi bi-trash-fill"></i> Видалити</a>
        </form>
    </div>
{% endblock content %}